# Config file for automatic testing at travis-ci.org

language: python
matrix:
  include:
    - python: 3.6
      env: RUN_QUALITY=true
    - python: 3.5
      env: RUN_QUALITY=false
    - python: 3.4
      env: RUN_QUALITY=false
    - python: 2.7
      env: RUN_QUALITY=false

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

sudo: required
services:
  - docker

# Command to run tests, e.g. python setup.py test
script:
  - tox
  - if [ $RUN_QUALITY == true ]; then python3 setup.py quality; fi

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: apiology
  password:
    secure: "FSycOmgawVZEAgt4og0wx4JR8COq8yAUTV9Kx1o1C6oDTzuA4+Cfv6bqnyzwzdDX0Firiv8uP/9vW3+qhdGc0XSKQzPr82vib1JOOXYudgMQTed4QfGcyFK1CpQtGU7JTxYH1OHy7NC8jnag1wy7oPQ61WD9S+IlBUqFfFhbbq9BFqFaVPX7xPlrarSK+dYiPygIKP4lIIK6e0r2FVO4Rxiigpe5em81NkmT+BqUyV7WJUmx42uc2NY51+786c9ZcbjdCaxxL5ep/yMQpMhExeZ718Ko6Xrb6fzrDViWo/xcoukupGYm2osXda0jKjJpRu9RDlczY7gJO1Ihi4tL3j0Tnh7t5z2zHRRHYzXki598fSWGsP3T5yMx5WmVnQJh9Uye+mXxL0EWUFeTM3gKPig9EHQIo6ztCILNtrK26soL6zdzPOm8ULWARFp/lJZHtKAvCCwxzSXNnLB1V6PR5RGbu6YtrR1EFfaIaqh/oTnx0BuHzH1eFWqwPnhaKFkNHX/8gSKBKbr/yf1BLjRsU8SmCNUEnAlPYZ8gXdEY10OQX8w1eSIc0jZP1J3vHIHLeM5OYWpaSPT8n84yMpfAZYWDngavCKf3SGSZg5NcLhL6r10UMleTJymM3hbYHXgMA9YymuFmCSoF9p8MfpwURnvCPq+rXui14bMkBcgLc6I="
  on:
    tags: true
    repo: apiology/local_keychain_utils
    python: 3.6
