# Config file for automatic testing at travis-ci.org

language: python
matrix:
  include:
    - python: 3.7
      env: NEEDS_QUALITY_IMAGE=false
    - python: 3.6
      env: NEEDS_QUALITY_IMAGE=true

dist: xenial

before_install:
  - "if [ ${NEEDS_QUALITY_IMAGE:?} = true ]; then (docker pull apiology/quality:jumbo-latest &) ; fi"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -U tox-travis

sudo: required
services:
  - docker

# Command to run tests, e.g. python setup.py test
script:
  - tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: apiology
  password:
    secure: CqnHXOr2xdUj3b/vlLr2qwH1jNQ9bGMXkFWIo8ZJgq5Vp6MzjOo5w+yyUYuVoibZ0LrPPyNmt0xsock51jrkFwETzldhG8h1WmWL3Ha4U3sTV2mAqYGFiGiHmRG9QRswpf2w+od7+EK7FGbB0kGoVEoh+kA1848ibX74ARCQDil/rhy8QTvrbjv0Ra1K7Zrhp7hMJ5EmxlHrQTpNZm3sgd5j8AsMGzNo+gJxdqQqXeNmF+M6d5HTCR9UkYVtwuKiY4ILzuyc4CduVyawVUWnk2LT3wGFg3sJ2dad1Q/l/Bacnr8/Z9hZqSj1qReAnYkIe/iYFErG6iM9KTGKdZ4sAAgD8IDKPgK713wZnoH83PgrcK378uV04Jd6nZCfJkkseptroIE5hOWdjiyiRRWd4YTZdeoMvfSt8B0D+u4AJXfwYbbt4DGR/K+xFeJyqJNtWtyrtLAZm9gPCZ7d6To8M2H+VsNXPd9pqtuC/Wc3b4TqOfZZC0SDvowtQWkQftXM6AmZqOV4dZ5LlIbwokeIGT4QaxryjGN7xElPYVtiNayWz7la/6K9WzUD/JKzO1pnt8riWPCTSlulW+U190IDogqa9Y1n37yaQmc5vyIp8bGzsACef9f0i069MuszpLXgiB7zT7AT7FQQ0UWi23hBslTpFjoQGUu4odXcEORXb6o=
  on:
    tags: true
    repo: apiology/local_keychain_utils
    python: 3.6
